config/routes.rb
Rails.application.routes.draw do
  resources :coperates
  resources :officers
  resources :companys
  resources :historys
  resources :informations
  resources :i_rmains
  resources :publications
  resources :pressses
  get 'admins/home'
  devise_for :users
  resources :notices
  resources :media
  resources :newzs 
  resources :admins
  resources :recruits
  resources :environments
  resources :footer
  resources :terms
  resources :policys
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "welcome#index", as: 'home'
  resources :products
  resources :clientproducts
  resources :contacts, only: [:new, :create, :index]
  get 'new' => 'contacts#new', as:'new' 
  get 'get_newzs', to: 'newzs#get_newzs'
  get 'show_newzs', to: 'newzs#show_newzs'
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :Companyname
  attribute :message
  attribute :nickname,  :captcha  => true
  attr_accessor :terms
  validates_acceptance_of :terms
  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form",
      :to => "mujtaba.testing54321@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/i_rmain.rb
class IRmain < ApplicationRecord
end

app/models/media.rb
class Media < ApplicationRecord
	# belongs_to :newz
end

app/models/newz.rb
class Newz < ApplicationRecord
	# belongs_to :admin
	has_many :notices 
	validates :title, presence: true, length: {minimum: 3}
end

app/models/notice.rb
class Notice < ApplicationRecord
	belongs_to :newz
end

app/models/presss.rb
class Presss < ApplicationRecord
end

app/models/publication.rb
class Publication < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.paginate(:page => params[:page], per_page: 3)
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notice_params
      params.require(:notice).permit(:title, :notice_date, :body)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/companys_helper.rb
module CompanysHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/historys_helper.rb
module HistorysHelper
end

app/helpers/i_rmains_helper.rb
module IRmainsHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/newzs_helper.rb
module NewzsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/policy_helper.rb
module PolicyHelper
end

app/helpers/policys_helper.rb
module PolicysHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/notices/_form.html.erb
<%= form_with(model: notice, local: true) do |form| %>
  <% if notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
        <% notice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :notice_date %>
    <%= form.date_select :notice_date %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/help.html.erb
<% render :template => 'notices/index'  %>

app/views/notices/index.html.erb
<%= render partial: "/layouts/navbar_coperatesite" %>

<!--==========================
    Intro Section
  ============================-->
  <section id="intro" class="clearfix">
    <div class="container">

      <div class="intro-img">
        
        <%= image_tag("intro-img.svg", :alt => "Flexslider" , :class => "img-fluid")%>
      </div>

      <div class="intro-info">
        <h2>We provide<br><span>solutions</span><br>for your business!</h2>
        <div>
          <a href="#about" class="btn-get-started scrollto">Get Started</a>
          <a href="#services" class="btn-services scrollto">Our Services</a>
        </div>
      </div>

    </div>
  </section>
  <!-- #intro -->

  <!--==========================
      About Us Section
    ============================-->
     <section id="about">
      <div class="container">

        <header class="section-header">
          <h3>Idenbrid information</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </header>

        <div class="row about-container">

          <div class="col-lg-6 content order-lg-1 order-2">
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
            </p>

            <div class="icon-box wow fadeInUp">
              <div class="icon"><i class="fa fa-shopping-bag"></i></div>
              <h4 class="title"><a href="">Eiusmod Tempor</a></h4>
              <p class="description">Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi</p>
            </div>

            <div class="icon-box wow fadeInUp" data-wow-delay="0.2s">
              <div class="icon"><i class="fa fa-photo"></i></div>
              <h4 class="title"><a href="">Magni Dolores</a></h4>
              <p class="description">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
            </div>

            <div class="icon-box wow fadeInUp" data-wow-delay="0.4s">
              <div class="icon"><i class="fa fa-bar-chart"></i></div>
              <h4 class="title"><a href="">Dolor Sitema</a></h4>
              <p class="description">Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata</p>
            </div>

          </div>

          <div class="col-lg-6 background order-lg-2 order-1 wow fadeInUp">
            
             <%= image_tag("about-img.svg", :alt => "Flexslider" , :class => "img-fluid")%>
          </div>
        </div>

        <div class="row about-extra">
          <div class="col-lg-6 wow fadeInUp">
            
            <%= image_tag("about-extra-1.svg", :alt => "Flexslider" , :class => "img-fluid")%>
          </div>
          <div class="col-lg-6 wow fadeInUp pt-5 pt-lg-0">
            <h4>Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h4>
            <p>
              Ipsum in aspernatur ut possimus sint. Quia omnis est occaecati possimus ea. Quas molestiae perspiciatis occaecati qui rerum. Deleniti quod porro sed quisquam saepe. Numquam mollitia recusandae non ad at et a.
            </p>
            <p>
              Ad vitae recusandae odit possimus. Quaerat cum ipsum corrupti. Odit qui asperiores ea corporis deserunt veritatis quidem expedita perferendis. Qui rerum eligendi ex doloribus quia sit. Porro rerum eum eum.
            </p>
          </div>
        </div>

        <div class="row about-extra">
          <div class="col-lg-6 wow fadeInUp order-1 order-lg-2">
            
            <%= image_tag("about-extra-2.svg", :alt => "Flexslider" , :class => "img-fluid")%>
          </div>

          <div class="col-lg-6 wow fadeInUp pt-4 pt-lg-0 order-2 order-lg-1">
            <h4>Neque saepe temporibus repellat ea ipsum et. Id vel et quia tempora facere reprehenderit.</h4>
            <p>
             Delectus alias ut incidunt delectus nam placeat in consequatur. Sed cupiditate quia ea quis. Voluptas nemo qui aut distinctio. Cumque fugit earum est quam officiis numquam. Ducimus corporis autem at blanditiis beatae incidunt sunt. 
            </p>
            <p>
              Voluptas saepe natus quidem blanditiis. Non sunt impedit voluptas mollitia beatae. Qui esse molestias. Laudantium libero nisi vitae debitis. Dolorem cupiditate est perferendis iusto.
            </p>
            <p>
              Eum quia in. Magni quas ipsum a. Quis ex voluptatem inventore sint quia modi. Numquam est aut fuga mollitia exercitationem nam accusantium provident quia.
            </p>
          </div>
          
        </div>

      </div>
    </section> 
    


<p id="notice"><%= notice %></p>

<section id="services" class="section-bg">
  <div class="container">
    <header class="section-header">
      <h3>Notices section</h3>
    </header>
   <div class="row" id="newletterbox">
    <% @notices.each do |notice|%>
    
    <div class="col-lg-3 offset-lg-1 wow bounceInUp" data-wow-duration=" 1.4s">
      
      <div class="box" >
        <div class="title">
          <h5>Notice updates</h5>
          <!-- <div>Title:</div>
          <div>Notice date:</div>
          <div>Body:</div> -->
        </div>
        
          <h4 class="title"><%= notice.title %></h4>
          <p class="title1"><%= notice.notice_date %></p>
          <p class="description"><%= notice.body.first(80) %></p>
          <div>
            <%= link_to 'Show', notice, class:"btn btn-info" %>
            <% if current_user.admin %>
            <%= link_to 'Edit', edit_notice_path(notice), class:"btn btn-success" %>
            <%= link_to 'Destroy', notice, class:"btn btn-warning", method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
    </div>
    <% end %>
  </div>
</div>
<%= link_to 'Back', newzs_path,class:"btn btn-primary"  %>
  <%= will_paginate @notices,id:'paginate' %>
  <% if current_user.admin %>
  <%= link_to 'Create Notice', new_notice_path, class:"btn btn-primary" %>
  <% end %>
</section>


<%= render partial: "/layouts/footer" %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form', notice: @notice %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<header id="header" class="fixed-top">
    <div class="container">

      <div class="logo float-left">
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <h1 class="text-light"><a href="#header"><span>NewBiz</span></a></h1> -->
        <a href="#intro" class="scrollto"><%= image_tag("logo.png", :alt => "Flexslider" , :class => "img-responsive")%></a>
      </div>

      <nav class="main-nav float-right d-none d-lg-block">
        <ul>
          <li class="active"><%= link_to "Coperate Website", home_path %></li>
          <li><a href="#about">IR information</a></li>
          <li><a href="#products">Product</a></li>
          <li><a href="#team">Employment Information</a></li>
          <li><a href="#services">news</a></li>
          <li class="nav-item"><%= link_to "Contact", new_contact_path %></li>
          <li class="nav-item"><%= link_to "Admin", admins_home_path %></li>
        </ul>
      </nav><!-- .main-nav -->
      
    </div>
  </header><!-- #header -->

<p id="notice"><%= notice %></p>

<section id="services" class="section-bg">
      <div class="container">

        <header class="section-header">
          <h3>Notices section</h3>
        </header>

        <div class="row">

          <div class="col-md-9 col-lg-9 offset-lg-1 wow bounceInUp" data-wow-duration="1.4s">
            <div class="box">
              <div class="icon"><i class="ion-ios-analytics-outline" style="color: #ff689b;"></i></div>
              <h4 class="title"><%= @notice.title %></h4>
              <p class="title1"><%= @notice.notice_date %></p>
              <p class="description"> <%= @notice.body %></p>
            </div>
          </div>
         </div>
     </div>
     <% if current_user.admin %>
      <%= link_to 'Edit', edit_notice_path(@notice) %> |
     <% end %>
     <%= link_to 'Back', notices_path %>
   </section><!-- #services -->


   <!--==========================
    Footer
  ============================-->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6 footer-info">
            <h3>NewBiz</h3>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus. Scelerisque felis imperdiet proin fermentum leo. Amet volutpat consequat mauris nunc congue.</p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><a href="#">Home</a></li>
              <li><a href="#">About us</a></li>
              <li><a href="#">Services</a></li>
              <li><a href="#">Terms of service</a></li>
              <li><a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>

          <div class="col-lg-3 col-md-6 footer-newsletter">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna veniam enim veniam illum dolore legam minim quorum culpa amet magna export quem marada parida nodela caramase seza.</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit"  value="Subscribe">
            </form>
          </div>

        </div>
         <div class="copyright">
           &copy; Copyright <strong>NewBiz</strong>. All Rights Reserved
        </div>
      </div>

    </div>

   
     
    
  </footer><!-- #footer -->