config/routes.rb
Rails.application.routes.draw do
  resources :coperates
  resources :officers
  resources :companys
  resources :historys
  resources :informations
  resources :i_rmains
  resources :publications
  resources :pressses
  get 'admins/home'
  devise_for :users
  resources :notices
  resources :media
  resources :newzs 
  resources :admins
  resources :recruits
  resources :environments
  resources :footer
  resources :terms
  resources :policys
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "welcome#index", as: 'home'
  resources :products
  resources :clientproducts
  resources :contacts, only: [:new, :create, :index]
  get 'new' => 'contacts#new', as:'new' 
  get 'get_newzs', to: 'newzs#get_newzs'
  get 'show_newzs', to: 'newzs#show_newzs'
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :Companyname
  attribute :message
  attribute :nickname,  :captcha  => true
  attr_accessor :terms
  validates_acceptance_of :terms
  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form",
      :to => "mujtaba.testing54321@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/i_rmain.rb
class IRmain < ApplicationRecord
end

app/models/media.rb
class Media < ApplicationRecord
	# belongs_to :newz
end

app/models/newz.rb
class Newz < ApplicationRecord
	# belongs_to :admin
	has_many :notices 
	validates :title, presence: true, length: {minimum: 3}
end

app/models/notice.rb
class Notice < ApplicationRecord
	belongs_to :newz
end

app/models/presss.rb
class Presss < ApplicationRecord
end

app/models/publication.rb
class Publication < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: [:show, :edit, :update, :destroy]

  # GET /publications
  # GET /publications.json
  def index
    @publications = Publication.paginate(:page => params[:page], per_page: 3)
  end

  # GET /publications/1
  # GET /publications/1.json
  def show
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications
  # POST /publications.json
  def create
    @publication = Publication.new(publication_params)

    respond_to do |format|
      if @publication.save
        format.html { redirect_to @publication, notice: 'Publication was successfully created.' }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1
  # PATCH/PUT /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to @publication, notice: 'Publication was successfully updated.' }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1
  # DELETE /publications/1.json
  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to publications_url, notice: 'Publication was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:title, :publication_date, :body)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/companys_helper.rb
module CompanysHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/historys_helper.rb
module HistorysHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/newzs_helper.rb
module NewzsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/policy_helper.rb
module PolicyHelper
end

app/helpers/policys_helper.rb
module PolicysHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication, local: true) do |form| %>
  <% if publication.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :publication_date %>
    <%= form.date_select :publication_date %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/edit.html.erb
<h1>Editing Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Show', @publication %> |
<%= link_to 'Back', publications_path %>

app/views/publications/index.html.erb
<%= render partial: "/layouts/navbar_coperatesite" %>

<p id="notice"><%= notice %></p>


<!--==========================
    Intro Section
  ============================-->
  <section id="intro" class="clearfix">
    <div class="container">

      <div class="intro-img">
        
        <%= image_tag("intro-img.svg", :alt => "Flexslider" , :class => "img-fluid")%>
      </div>

      <div class="intro-info">
        <h2>We provide<br><span>solutions</span><br>for your business!</h2>
        <div>
          <a href="#about" class="btn-get-started scrollto">Get Started</a>
          <a href="#services" class="btn-services scrollto">Our Services</a>
        </div>
      </div>

    </div>
  </section><!-- #intro -->


  <!--==========================
      Team Section
    ============================-->
     <section id="team">
      <div class="container">
        <div class="section-header">
          <h3>Employment Information</h3>
          <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque</p>
        </div>

        <div class="row">

          <div class="col-lg-3 col-md-6 wow fadeInUp">
            <div class="member">
              
              <%= image_tag("team-1.jpg", :alt => "Flexslider" , :class => "img-fluid")%>
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Walter White</h4>
                  <span>Chief Executive Officer</span>
                  <div class="social">
                    <a href=""><i class="fa fa-twitter"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
            <div class="member">
              <%= image_tag("team-2.jpg", :alt => "Flexslider" , :class => "img-fluid")%>
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Sarah Jhonson</h4>
                  <span>Product Manager</span>
                  <div class="social">
                    <a href=""><i class="fa fa-twitter"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.2s">
            <div class="member">
              <%= image_tag("team-3.jpg", :alt => "Flexslider" , :class => "img-fluid")%>
              <div class="member-info">
                <div class="member-info-content">
                  <h4>William Anderson</h4>
                  <span>CTO</span>
                  <div class="social">
                    <a href=""><i class="fa fa-twitter"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
            <div class="member">
              <%= image_tag("team-4.jpg", :alt => "Flexslider" , :class => "img-fluid")%>
              <div class="member-info">
                <div class="member-info-content">
                  <h4>Amanda Jepson</h4>
                  <span>Accountant</span>
                  <div class="social">
                    <a href=""><i class="fa fa-twitter"></i></a>
                    <a href=""><i class="fa fa-facebook"></i></a>
                    <a href=""><i class="fa fa-google-plus"></i></a>
                    <a href=""><i class="fa fa-linkedin"></i></a>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section> 
    <!-- #team -->


<section id="services" class="section-bg">
  <div class="container">
   <div class="row" id="newletterbox">
     <% @publications.each do |publication| %>
    
    <div class="col-md-3 col-lg-3 offset-lg-1 wow bounceInUp" data-wow-duration=" 1.4s">
      
      <div class="box" >
        <div class="title">
          <h5> Media </h5>
          <div>Title:</div>
          <div>Publish date:</div>
          <div>Body:</div>
        </div>
        
          <h4 class="title"><%= publication.title %></h4>
          <p class="title1"><%= publication.publication_date %></p>
          <p class="description"><%= publication.body %></p>
          <div>
            <%= link_to 'Show', publication, class:"btn btn-info" %>
            <%= link_to 'Edit', edit_publication_path(publication), class:"btn btn-success" %>
            <%= link_to 'Destroy', publication,class:"btn btn-warning", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        
      </div>
    </div>
    <% end %>
  </div>
  <%= will_paginate @publications,id:'paginate' %>
 </div>
 <%= link_to 'Back', newzs_path,class:"btn btn-primary"  %>
 <% if current_user.admin %>
 <%= link_to 'Create publications', new_publication_path, class:'btn btn-primary' %>
 <% end %>
 
</section><!-- #services -->
<%= render partial: "/layouts/footer" %>

app/views/publications/new.html.erb
<h1>New Publication</h1>

<%= render 'form', publication: @publication %>

<%= link_to 'Back', publications_path %>

app/views/publications/show.html.erb
<header id="header" class="fixed-top">
    <div class="container">

      <div class="logo float-left">
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <h1 class="text-light"><a href="#header"><span>NewBiz</span></a></h1> -->
        <a href="#intro" class="scrollto"><%= image_tag("logo.png", :alt => "Flexslider" , :class => "img-responsive")%></a>
      </div>

      <nav class="main-nav float-right d-none d-lg-block">
        <ul>
          <li class="active"><%= link_to "Coperate Website", home_path %></li>
          <li><a href="#about">IR information</a></li>
          <li><a href="#products">Product</a></li>
          <li><a href="#team">Employment Information</a></li>
          <li><a href="#services">news</a></li>
          <li class="nav-item"><%= link_to "Contact", new_contact_path %></li>
          <li class="nav-item"><%= link_to "Admin", admins_home_path %></li>
        </ul>
      </nav><!-- .main-nav -->
      
    </div>
  </header><!-- #header -->
<p id="notice"><%= notice %></p>

<section id="services" class="section-bg">
      <div class="container">

        <header class="section-header">
          <h3>Notices section</h3>
          
        </header>

        <div class="row">

          <div class="col-md-9 col-lg-9 offset-lg-1 wow bounceInUp" data-wow-duration="1.4s">
            <div class="box">
              <div class="icon"><i class="ion-ios-analytics-outline" style="color: #ff689b;"></i></div>
              <h4 class="title"><%= @publication.title %></h4>
              <p class="title1"><%= @publication.publication_date %></p>
              <p class="description"> <%= @publication.body %></p>
            </div>
          </div>
         </div>
     </div>
     <% if current_user.admin %>
      <%= link_to 'Edit', edit_publication_path(@publication) %> |
      <% end %>
     <%= link_to 'Back', publications_path %>
 </section>


 <!-- #services -->
<!--==========================
    Footer
  ============================-->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-4 col-md-6 footer-info">
            <h3>NewBiz</h3>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus. Scelerisque felis imperdiet proin fermentum leo. Amet volutpat consequat mauris nunc congue.</p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><a href="#">Home</a></li>
              <li><a href="#">About us</a></li>
              <li><a href="#">Services</a></li>
              <li><a href="#">Terms of service</a></li>
              <li><a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>

          <div class="col-lg-3 col-md-6 footer-newsletter">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna veniam enim veniam illum dolore legam minim quorum culpa amet magna export quem marada parida nodela caramase seza.</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit"  value="Subscribe">
            </form>
          </div>

        </div>
         <div class="copyright">
           &copy; Copyright <strong>NewBiz</strong>. All Rights Reserved
        </div>
      </div>

    </div>

   
     
    
  </footer><!-- #footer -->