config/routes.rb
Rails.application.routes.draw do
  resources :coperates
  resources :officers
  resources :companys
  resources :historys
  resources :informations
  resources :i_rmains
  resources :publications
  resources :pressses
  get 'admins/home'
  devise_for :users
  resources :notices
  resources :media
  resources :newzs 
  resources :admins
  resources :recruits
  resources :environments
  resources :footer
  resources :terms
  resources :policys
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "welcome#index", as: 'home'
  resources :products
  resources :clientproducts
  resources :contacts, only: [:new, :create, :index]
  get 'new' => 'contacts#new', as:'new' 
  get 'get_newzs', to: 'newzs#get_newzs'
  get 'show_newzs', to: 'newzs#show_newzs'
end

app/models/admin.rb
class Admin < ApplicationRecord
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :Companyname
  attribute :message
  attribute :nickname,  :captcha  => true
  attr_accessor :terms
  validates_acceptance_of :terms
  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form",
      :to => "mujtaba.testing54321@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/i_rmain.rb
class IRmain < ApplicationRecord
end

app/models/media.rb
class Media < ApplicationRecord
	# belongs_to :newz
end

app/models/newz.rb
class Newz < ApplicationRecord
	# belongs_to :admin
	has_many :notices 
	validates :title, presence: true, length: {minimum: 3}
end

app/models/notice.rb
class Notice < ApplicationRecord
	belongs_to :newz
end

app/models/presss.rb
class Presss < ApplicationRecord
end

app/models/publication.rb
class Publication < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/newzs_controller.rb
class NewzsController < ApplicationController
  before_action :set_newz, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show ,:index, :get_newzs,:show_newzs]
  

  def get_newzs
    @newzs = Newz.paginate(:page => params[:page], per_page: 6)
  end  

  def show_newzs
     
    @newz = Newz.where(id: params[:format].to_i).last
  end   
  # GET /newzs
  # GET /newzs.json
  def index
    @newzs = Newz.paginate(:page => params[:page], per_page: 6)
  end

  # GET /newzs/1
  # GET /newzs/1.json
  def show
  end

  # GET /newzs/new
  def new
    @newz = Newz.new
  end

  # GET /newzs/1/edit
  def edit
  end

  # POST /newzs
  # POST /newzs.json
  def create
    @newz = Newz.new(newz_params)

    respond_to do |format|
      if @newz.save
        format.html { redirect_to @newz, notice: 'Newz was successfully created.' }
        format.json { render :show, status: :created, location: @newz }
      else
        format.html { render :new }
        format.json { render json: @newz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newzs/1
  # PATCH/PUT /newzs/1.json
  def update
    respond_to do |format|
      if @newz.update(newz_params)
        format.html { redirect_to @newz, notice: 'Newz was successfully updated.' }
        format.json { render :show, status: :ok, location: @newz }
      else
        format.html { render :edit }
        format.json { render json: @newz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newzs/1
  # DELETE /newzs/1.json
  def destroy
    @newz.destroy
    respond_to do |format|
      format.html { redirect_to newzs_url, notice: 'Newz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newz
      @newz = Newz.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def newz_params
      params.require(:newz).permit(:names, :title, :publish_date, :body)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/companys_helper.rb
module CompanysHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/footer_helper.rb
module FooterHelper
end

app/helpers/historys_helper.rb
module HistorysHelper
end

app/helpers/i_rmains_helper.rb
module IRmainsHelper
end

app/helpers/media_helper.rb
module MediaHelper
end

app/helpers/newzs_helper.rb
module NewzsHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/policy_helper.rb
module PolicyHelper
end

app/helpers/policys_helper.rb
module PolicysHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/newzs/_form.html.erb
<%= form_with(model: newz, local: true) do |form| %>
  <% if newz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(newz.errors.count, "error") %> prohibited this newz from being saved:</h2>

      <ul>
        <% newz.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :names %>
    <%= form.text_field :names %>
  </div>
  
  <div class="field">
    <%= form.label :publish_date %>
    <%= form.date_select :publish_date %>
  </div>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>


  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/newzs/edit.html.erb
<h1>Editing Newz</h1>

<%= render 'form', newz: @newz %>

<%= link_to 'Show', @newz %> |
<%= link_to 'Back', newzs_path %>

app/views/newzs/get_newzs.html.erb
<%= render partial: "/layouts/navbar_coperatesite" %>





<!-- Facebook -->
<!--  <a class="fb-ic" href="https://www.facebook.com/zindawork/" target="_blank"><i class="fa fa-facebook" style="font-family: normal normal normal 14px/1 FontAwesome"></i> </a> -->

<!--Instagram-->
<!--  <a class="ins-ic" href="https://www.instagram.com/zindawork/?utm_source=ig_embed" target="_blank"> <i class="fa fa-instagram"> </i> </a> -->
          
<style type="text/css">
  *:focus{
    outline: none;
    }
  
  body{
    
    overflow-x: hidden;
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    }
  .entry-item {
    width: 100%;
    height: auto;
    margin-right: 20px;
    margin-bottom: 26px;
    padding: 20px;
    box-sizing: border-box;
    display: block;
    background: #fff;
    box-shadow: 0 2px 6px 0 rgba(0,0,0,.07);
    transition: all 300ms;
    }
  .category {
    font-size: 14px;
    font-weight: 600;
    letter-spacing: 1px;
  }
  .category.press_release {
    color: #943ce1;
  }
  .date {
    font-size: 13px;
    font-weight: normal;
    color: rgba(0,0,0,.4);
  }
  .entry-title {
    font-size: 14px;
    font-weight: 600;
    line-height: 1.71;
    letter-spacing: .6px;
    color: #45494b;
    overflow: hidden;
    display: -webkit-box;
    height: 45px;
    margin-top: 30px;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 2;
  }
  .entry-content {
    font-size: 12px;
    font-weight: 400;
    line-height: 1.83;
    margin-top: 15px;
    height: 66px;
    color: rgba(0,0,0,.6);
    overflow: hidden;
    display: -webkit-box;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 3;
  }
  *:focus{
              outline: none;
            }

            body{
              overflow-x: hidden;
              margin: 0;
              font-family: 'Libre Franklin', sans-serif;
              padding: 0;
              box-sizing: border-box;
            }
            p{
              font-size: 100%;
              line-height: 2;
              letter-spacing: 1.2px;
              color: #9DA0A4 !important;
            }
            strong  {
              color:#000 !important;
            }
            ul li {
              font-size: 110%;
    line-height: 1.45;
    letter-spacing: 1.2px;
    font-weight: 500;
    z-index: 5;
            }
            .listUl a {
             color: #9DA0A4 !important;
              text-decoration: none;
              background-color: transparent;
          }
            .listUl  a:hover {
             color: #9DA0A4;
              text-decoration: none;
              background-color: transparent;
          }  
  .entry-item:hover {
    transform: translateY(-6px);
    box-shadow: 0 6px 6px 0 rgba(0,0,0,.1);
    text-decoration: none;
  }
  .category.medium {
    color: #1ecc6f;
  }
  label{
  
  font-size: 100%;
   }
  a:hover {
    color: #0056b3;
    text-decoration: none;
   }
  option{
  border-color: #0000000d;
   }
  .selrctNews{
    border-color: #0000000d;
    word-wrap: normal;
    width: 340px;
    font-size: 13px;
    color: #00000099;
    padding: 10px;

  }
  #paginate span, #paginate em, #paginate a{
padding: 0 10px;
  }
  
 #paginate{
  justify-content:center; 
  color:grey !important;
}

 @media(max-width: 600px){
  .onmmt-5vh{
    margin-top: 20vh !important;
  }
  .d-blockm{
    display: block !important;
    width: 100%;
  }
  .selrctNews {
    width: 100%;
}
 }
</style>

<div class="col-md-9 mx-auto my-5 onmmt-5vh">
  <div class="row m-0 ">
    <div class="my-3 d-flex d-blockm">
      <div>
        <label>Year</label> <br>
      <select class="selrctNews mr-3">
        <option>all</option>
        <option>2020</option>
        <option>2019</option>
        <option>2018</option>
        <option>2017</option>
        <option>2016</option>
      </select>
      </div>

       <div>
        <label>Category</label> <br>
      <select class="selrctNews mr-3">
        <option>all</option>
        <option>Press release</option>
        <option>Notice</option>
        <option>Publication</option>
      </select>
      </div>
    </div>
  </div>
  <br><br>
  <div class="row">
    <% @newzs.each do |newz| %>
      <div class="col-md-4">
        <a target="_blank" class="entry-item" href="<%= show_newzs_path(newz.id) %>"><div class="entry-header">
      <div class="category press_release"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> 
       <%= newz.names %>
      </font></font></div>
      <div class="date"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><%= newz.publish_date %></font></font></div>
      </div>
      <div class="entry-title"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><%= newz.title %></font></font></div>
      <div class="entry-content"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><%= newz.body.first(80) %></font></font></div>
      </a>
      </div>
    <% end %>
    
  </div>
 
 <%= will_paginate @newzs,id:'paginate' %>

</div>

  <%= render partial: "/layouts/footer" %>




<script type="text/javascript">
  $('.newz_id').click(function(){
var pub_id = $(this).data('id');
debugger
$.ajax({
type: 'POST',
url:'/get_newzs',
data: {newz: {pub_id: newz_id}},
success: function(data){
}
});
});


</script>  
<script type="text/javascript">
  $(document).ready(function(){
    $("#barMenu").click(function(){
      $("#barMenu").css("display", "none");
      $("#closeMenu").css("display", "Inline-table");
      $("body").css("overflow", "hidden");
      $(".onmmt-5vh, .footer").css("opacity", ".2");
    });
  });
  $(document).ready(function(){
    $("#closeMenu").click(function(){
      $("#closeMenu").css("display", "none");
      $("#barMenu").css("display", "block");
      $("body").css("overflow", "auto");
      $(".onmmt-5vh, .footer").css("opacity", "1")
    });
  });
</script>

app/views/newzs/index.html.erb
<%= render partial: "/layouts/navbar_coperatesite" %>
<style type="text/css">
  ul li {
    font-size: 110%;
    line-height: 1.45;
    letter-spacing: 1.2px;
    font-weight: 500;
    margin-bottom: 1rem;
    z-index: 5;
            }
    .sns-buttons li{
      margin-bottom: 0 !important;
     }

  #paginate{
  justify-content:center; 
  color:grey;
   }          
</style>
<p id="notice"><%= notice %></p>


<section id="services" class="section-bg">
  <div class="col-md-9 mx-auto opcity2">
   <header class="section-header text-center">
    <h3 class="text-capitalize pt-5">NEWS</h3>
        <div class="lead-sub" style="color: #9e9e9e">NEWS</div>
   </header>
  <div class="col-md-9 mx-auto mt-5">
    <div class="row">
      <div class="col-lg-3 offset-lg-1 wow bounceInUp mb-3" data-wow-duration="1.4s">
        <label>Year</label>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            All
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
             <p class="title1"><%= %></p>
            <a class="dropdown-item" href="#" style="color:black;">All</a>
            <a class="dropdown-item" href="#">2020</a>
            <a class="dropdown-item" href="#">2019</a>
          </div>
        </div>
      </div>
      <div class="col-lg-3 offset-lg-1 wow bounceInUp mb-3" data-wow-duration="1.4s">
        <label>Category</label>
      <div class="dropdown">
       <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          All
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          
          <%= link_to "Press release", pressses_path, class:'dropdown-item',style:"color:black;" %>
          <%= link_to "Notice", notices_path, class:'dropdown-item',style:"color:black;" %>
          <%= link_to "Publication", publications_path, class:'dropdown-item',style:"color:black;" %>
        </div>
      </div>
    </div>
   </div>
  </div></br>
  <div class="row" id="newletterbox">
    <% @newzs.each do |newz| %>
    
    <div class="col-lg-8 col-md-6 offset-lg-1">
      
      <div class="box" >
        <div class="title">
          <h5> Media </h5>
        </div>  
        
          <h4 class="title"><%= newz.names %></h4>
          <h4 class="title"><%= newz.title %></h4>
          <p class="title1"><%= newz.publish_date %></p>
          <p class="description"><%= newz.body.first(80) %></p>
          <div>

           
            <%= link_to 'Show', newz, class:"btn btn-info" %>
            <% if current_user.admin %>
             <%= link_to 'Edit', edit_newz_path(newz), class:"btn btn-success" %>
             
             <%= link_to 'Destroy', newz,class:"btn btn-warning", method: :delete, data: { confirm: 'Are you sure?'} %>
             
             
            <% end %>
          </div>
        
      </div>
    </div>
    <% end %>
  </div>
  <%= will_paginate @newzs,id:'paginate' %>

 
 <%= link_to 'Create News', new_newz_path, class:'btn btn-primary' %>
</section><!-- #services -->
<% if current_user.admin %>
  <%= render partial: "/layouts/footer" %>
<%end%>  

app/views/newzs/new.html.erb
<h1>New Newz</h1>

<%= render 'form', newz: @newz %>

<%= link_to 'Back', newzs_path %>

app/views/newzs/show.html.erb
<p id="notice"><%= notice %></p>
  <section id="services" class="section-bg">
      <div class="container">

        <header class="section-header">
          <h3>News</h3>
          <p>news</p>
        </header>

        <div class="row">

          <div class="col-md-9 col-lg-9 offset-lg-1 wow bounceInUp" data-wow-duration="1.4s">
            <div class="box">
              <div class="icon"><i class="ion-ios-analytics-outline" style="color: #ff689b;"></i></div>
              <h4 class="title"><%= @newz.names %></h4>
              <h4 class="title"><%= @newz.title %></h4>
              <p class="title1"><%= @newz.publish_date %></p>
              <p class="description"> <%= @newz.body %></p>
            </div>
          </div>
         </div>
     </div>
     <% if current_user.admin %>
     <%= link_to 'Edit', edit_newz_path(@newz) %> |
     <% end %>
     <%= link_to 'Back', newzs_path %>
   </section><!-- #services -->
   

app/views/newzs/show_newzs.html.erb


  <section id="services" class="section-bg">
      <div class="container">

        <header class="section-header">
          <h3>News</h3>
          <p>news</p>
        </header>

        <div class="row">

          <div class="col-md-10 col-lg-12">
            <div class="box">
              <div class="icon"><i class="ion-ios-analytics-outline" style="color: #ff689b;"></i></div>
              <h4 class="title"><%= @newz.names %></h4>
              <h4 class="title"><%= @newz.title %></h4>
              <p class="title1"><%= @newz.publish_date %></p>
              <p class="description"> <%= @newz.body %></p>
            </div>
          </div>
         </div>
     </div>
    <div class="text-left">
     <%= link_to 'Back', get_newzs_path , class:"btn btn-info"%>
   </div>
   </section><!-- #services -->
   